// Shared formatting utilities (replaces mock-file fmtRp)
export const fmtRp = (n: number) => `Rp ${n.toLocaleString("id-ID")}`;
export const fmtJpy = (n: number) => `¥${n.toLocaleString("ja-JP")}`;

export const STATUS_LABEL: Record<string, string> = {
  draft: "Draft",
  quote_created: "Quote dibuat",
  waiting_payment: "Menunggu pembayaran",
  paid: "Dibayar",
  procurement_queue: "Antrian beli",
  purchased: "Dibeli di Jepang",
  in_japan_warehouse: "Gudang Tokyo",
  packed: "Dikemas",
  shipped_to_indonesia: "Dikirim ke Indo",
  customs_clearance: "Bea cukai",
  last_mile_delivery: "Last-mile",
  delivered: "Sampai",
  cancelled: "Dibatalkan",
  refunded: "Refund",
  active: "Aktif",
  expired: "Kedaluwarsa",
  converted: "Dikonversi",
  monitoring: "Monitoring",
  triggered: "Tercapai!",
  open: "Open",
  in_progress: "In Progress",
  resolved: "Selesai",
  pending: "Pending",
  settled: "Selesai",
  failed: "Gagal",
  pending_review: "Review",
  approved: "Disetujui",
  processing: "Diproses",
  completed: "Selesai",
};

export const STATUS_TONE: Record<string, string> = {
  draft: "bg-muted text-muted-foreground",
  quote_created: "bg-secondary text-foreground",
  waiting_payment: "bg-warning/15 text-warning",
  paid: "bg-success/15 text-success",
  procurement_queue: "bg-primary-soft text-primary",
  purchased: "bg-primary-soft text-primary",
  in_japan_warehouse: "bg-primary-soft text-primary",
  packed: "bg-primary-soft text-primary",
  shipped_to_indonesia: "bg-primary-soft text-primary",
  customs_clearance: "bg-warning/15 text-warning",
  last_mile_delivery: "bg-primary-soft text-primary",
  delivered: "bg-success/15 text-success",
  cancelled: "bg-destructive/15 text-destructive",
  refunded: "bg-muted text-muted-foreground",
  active: "bg-success/15 text-success",
  expired: "bg-muted text-muted-foreground",
  converted: "bg-primary-soft text-primary",
  monitoring: "bg-primary-soft text-primary",
  triggered: "bg-success/15 text-success",
  open: "bg-warning/15 text-warning",
  in_progress: "bg-primary-soft text-primary",
  resolved: "bg-success/15 text-success",
  pending: "bg-warning/15 text-warning",
  settled: "bg-success/15 text-success",
  failed: "bg-destructive/15 text-destructive",
  pending_review: "bg-warning/15 text-warning",
  approved: "bg-primary-soft text-primary",
  processing: "bg-warning/15 text-warning",
  completed: "bg-success/15 text-success",
  closing_soon: "bg-warning/15 text-warning",
  shipping: "bg-primary-soft text-primary",
  closed: "bg-muted text-muted-foreground",
};
